### ISSUE TITLE
[TicTacToe] Хардкод

### ISSUE THREAD

**Issue by pavel-b-novikov** [9010v1n/nsudotnet#1]
Боже, мои глаза...
Ну зачем, зачем вы делаете 81 кнопку руками? Ну откуда пришло такое решение? Ну ItemsControl кому дарован свыше? 

Срочно переделать на ItemsControl + UniformGrid, убрать этот говнокод, а дальше уже поймете что не так с моделями.

Черт, вам дали WPF, а вы пользуетесь им как WinForms.

P.S> Я заценил дизайн, да. Углядел его в маленький кусочек монитора, который не был забрызган кровью из глаз.

**Comment by 9010v1n** [comment]
В общем, я вернул к консольной версии в нормальном виде. Можете проверить её, и сделал еще задачу Enigma

**Comment by pavel-b-novikov** [comment]
Ладно, WPF не для всех. Консоль так консоль.
