### ISSUE TITLE
[TicTacToe] Lazy

### ISSUE THREAD

**Issue by pavel-b-novikov** [9010v1n/nsudotnet#2]
Объясните зачем нужен Lazy<> и конкретно с какой целью Gamecontroller обернут в него?

**Comment by pavel-b-novikov** [comment]
В остальном, кстати, сегрегация сделано верно. Придираться не буду. Однако после попытки изготовления UI - кто б сегрегацию не сделал верно...

**Comment by 9010v1n** [comment]
Конкретно в данном случае таким образом разрешается циклическая зависимость между контроллером и представлением на этапе компиляции. Связывание происходит в райнтайме при первом обращении

**Comment by pavel-b-novikov** [comment]
Так, если у вас циклическая зависимость между контроллером и View, значит декомпозиция сделана неправильно. Lazy<> быть не должно. Думайте-разгребайте.

**Comment by 9010v1n** [comment]
Убрал циклическую зависимость через event

**Comment by pavel-b-novikov** [comment]
Какой молодец
