### ISSUE TITLE
[Enigma] Парсеринг

### ISSUE THREAD

**Issue by pavel-b-novikov** [9010v1n/nsudotnet#3]
Меня удивляет как некоторые люди разводят целую эпопею вокруг переключения алгоритмов. То есть я правильно понимаю, что вы парсите имя алгоритма в enum, потом используете значение enum-а чтобы создать экземпляр CSP?

**Comment by 9010v1n** [comment]
Сейчас так работает. Погуглив, я не нашел способа получения конкретной реализации CSP по имени алгоритма. В способе с enum-ом switch по выбору реализации CSP уходит из логики работы методов encrypt и decrypt

**Comment by 9010v1n** [comment]
Не понял, нужно ли исправлять и как должно быть. Отпишитесь.

**Comment by pavel-b-novikov** [comment]
Нет, меня смущает именно последовательность действий: строка - enum - csp. Это явный перебор. Вы или крестик снимите (переделайте на свитч по строкам), или трусы наденьте (уберите переключение по строкам - делайте Enum.Parse из входных параметров с ToUpper/ToLower при необходимости)

**Comment by 9010v1n** [comment]
Я не понимаю в чем проблема. Где эта цепочка: строка - enum - csp. Строка изначально при валидации аргументов парсится в enum, а потом уже когда нужен алгоритм, он парсится из enum-а(нет последовательности строка-enum-csp для получения). Вы хотите чтобы я сразу парсил из строки в csp на стадии валидации аргументов? Просто csp, наверное, не спроста реализует интерфейс IDisposable и его лучше создать там, где он используется, и обернуть в using, а это можно сделать только если парсить 2 раза строку(на стадии проверки и при использовании), либо как я сделал (вначале строка, а потом из enum-а)

**Comment by 9010v1n** [comment]
Жду ответа

**Comment by pavel-b-novikov** [comment]
Ой, ладно, пусть будет по-вашему.
